### ISSUE TITLE
bug with USB 3 port 

### ISSUE THREAD

**Issue by ergrelet** [benureau/pydyn#20]
``` bash
Connecting to the serial controller...
Traceback (most recent call last):
  File "zero.py", line 2, in <module>
    mset = pydyn.MotorSet()
  File "/net/cremi/ergrelet/.local/lib/python2.7/site-packages/pydyn/msets/msets.py", line 23, in __init__
    dyn_uid  = hub.connect(**kwargs) # TODO treat n
  File "/net/cremi/ergrelet/.local/lib/python2.7/site-packages/pydyn/dynamixel/hub.py", line 85, in connect
    broadcast_ping=broadcast_ping)
  File "/net/cremi/ergrelet/.local/lib/python2.7/site-packages/pydyn/ios/serialio/serialio.py", line 143, in __init__
    ports = available_ports(enable_pyftdi=enable_pyftdi)
  File "/net/cremi/ergrelet/.local/lib/python2.7/site-packages/pydyn/ios/serialio/serialio.py", line 44, in available_ports
    ports = list(list_ports.list_ports_by_vid_pid())
  File "/net/cremi/ergrelet/.local/lib/python2.7/site-packages/pydyn/ios/serialio/list_ports.py", line 50, in list_ports_by_vid_pid
    ports = comports()
  File "/usr/lib/python2.7/dist-packages/serial/tools/list_ports_posix.py", line 122, in comports
    return [(d, describe(d), hwinfo(d)) for d in devices]
  File "/usr/lib/python2.7/dist-packages/serial/tools/list_ports_posix.py", line 93, in describe
    return usb_lsusb_string(sys_usb)
  File "/usr/lib/python2.7/dist-packages/serial/tools/list_ports_posix.py", line 80, in usb_lsusb_string
    return base
NameError: global name 'base' is not defined
```

**Comment by benureau** [comment]
@ergrelet: so this is an ancient bug, but it seems this is an upstream bug from the `serial` package, unrelated to `pydyn`. I am closing this.
